In [7]:
import numpy as np

vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
matrix = np.zeros((3, 3))
print("\nДвовимірний масив розміром 3x3:")
print(matrix)


Двовимірний масив розміром 3x3:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
random_matrix = np.random.randint(1, 11, (5, 5))
print("\nМасив розміром 5x5,:")
print(random_matrix)


Масив розміром 5x5,:
[[ 3  8  7 10  9]
 [ 7  7  4  8  2]
 [ 6  1  4 10  4]
 [ 1  4  9  8  6]
 [ 6  8  8 10  7]]


In [9]:
random_float_matrix = np.random.uniform(0, 1, (4, 4))
print("\nМасив розміром 4x4:")
print(random_float_matrix)


Масив розміром 4x4:
[[0.93236583 0.97464956 0.47241392 0.88045261]
 [0.34283076 0.35966074 0.56819986 0.6359443 ]
 [0.45731737 0.07886957 0.6655445  0.57086315]
 [0.36171522 0.19944875 0.51040512 0.4366337 ]]


In [10]:
# Завдання 5
vector1 = np.random.randint(1, 11, 5)
vector2 = np.random.randint(1, 11, 5)
print("\nмасив 1:")
print(vector1)
print("масив 2:")
print(vector2)
print("Додавання:", vector1 + vector2)
print("Віднімання:", vector1 - vector2)
print("Множення:", vector1 * vector2)


масив 1:
[2 5 8 2 9]
масив 2:
[2 2 4 7 3]
Додавання: [ 4  7 12  9 12]
Віднімання: [ 0  3  4 -5  6]
Множення: [ 4 10 32 14 27]


In [11]:
# Завдання 6
vector3 = np.random.randint(1, 11, 7)
vector4 = np.random.randint(1, 11, 7)
print("\nСкалярний добуток двох векторів:")
print(np.dot(vector3, vector4))


Скалярний добуток двох векторів:
239


In [12]:
# Завдання 7
matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 3))
print("\nДві матриці розміром 2x2 та 2x3, перемножені між собою:")
print(np.dot(matrix1, matrix2))


Дві матриці розміром 2x2 та 2x3, перемножені між собою:
[[52 90 78]
 [54 95 81]]


In [13]:
# Завдання 8
matrix3 = np.random.randint(1, 11, (3, 3))
print("\nМатриця розміром 3x3, обернена матриця:")
print(np.linalg.inv(matrix3))


Матриця розміром 3x3, обернена матриця:
[[-0.78125   0.578125  0.0625  ]
 [ 0.4375   -0.34375   0.125   ]
 [ 0.0625    0.09375  -0.125   ]]


In [14]:
# Завдання 9
matrix4 = np.random.uniform(0, 1, (4, 4))
print("\nМатриця розміром 4x4, транспонована матриця:")
print(matrix4.T)


Матриця розміром 4x4, транспонована матриця:
[[0.80767215 0.32873559 0.46075331 0.0057068 ]
 [0.85232252 0.48022563 0.24933939 0.73494684]
 [0.95778865 0.86405644 0.88450344 0.54552632]
 [0.4996966  0.83940038 0.45544131 0.02849444]]


In [15]:
# Завдання 10
matrix5 = np.random.randint(1, 11, (3, 4))
vector5 = np.random.randint(1, 11, 4)
print("\nМатриця розміром 3x4 та вектор розміром 4, перемножена матрицю на вектор:")
print(np.dot(matrix5, vector5))


Матриця розміром 3x4 та вектор розміром 4, перемножена матрицю на вектор:
[167 112 125]


In [16]:
# Завдання 11
matrix6 = np.random.uniform(0, 1, (2, 3))
vector6 = np.random.uniform(0, 1, 3)
print("\nМатриця розміром 2x3 та вектор розміром 3, перемножена матрицю на вектор:")
print(np.dot(matrix6, vector6))


Матриця розміром 2x3 та вектор розміром 3, перемножена матрицю на вектор:
[0.77562683 0.99375868]


In [17]:
# Завдання 12
matrix7 = np.random.randint(1, 11, (2, 2))
matrix8 = np.random.randint(1, 11, (2, 2))
print("\nДві матриці розміром 2x2, поелементне множення:")
print(matrix7 * matrix8)


Дві матриці розміром 2x2, поелементне множення:
[[35 20]
 [35 70]]


In [18]:
# Завдання 13
print("\nДві матриці розміром 2x2, добуток:")
print(np.dot(matrix7, matrix8))


Дві матриці розміром 2x2, добуток:
[[ 63  53]
 [105  95]]


In [19]:
# Завдання 14
matrix9 = np.random.randint(1, 101, (5, 5))
print("\nМатриця розміром 5x5, сума елементів:")
print(np.sum(matrix9))


Матриця розміром 5x5, сума елементів:
1324


In [20]:
# Завдання 15
matrix10 = np.random.randint(1, 11, (4, 4))
matrix11 = np.random.randint(1, 11, (4, 4))
print("\nДві матриці розміром 4x4, різниця:")
print(matrix10 - matrix11)


Дві матриці розміром 4x4, різниця:
[[ 4  6 -1 -6]
 [-9  3  1  2]
 [ 4  4 -2 -3]
 [-2 -2  3 -4]]


In [21]:
# Завдання 16
matrix12 = np.random.uniform(0, 1, (3, 3))
print(np.sum(matrix12, axis=1))

[0.75929675 1.4801763  2.06860324]


In [22]:
# Завдання 17
matrix13 = np.random.randint(1, 11, (3, 4))
print("\nМатриця розміром 3x4 з довільними цілими числами:")
print(matrix13)
print("Матриця з квадратами цих чисел:")
print(matrix13**2)


Матриця розміром 3x4 з довільними цілими числами:
[[ 3  5  2  5]
 [ 8  9 10  4]
 [ 1  8  9  8]]
Матриця з квадратами цих чисел:
[[  9  25   4  25]
 [ 64  81 100  16]
 [  1  64  81  64]]


In [23]:
# Завдання 18
vector7 = np.random.randint(1, 51, 4)
print("\nВектор розміром 4, заповнений випадковими цілими числами в діапазоні від 1 до 50:")
print(vector7)
print("Вектор з квадратними коренями цих чисел:")
print(np.sqrt(vector7))


Вектор розміром 4, заповнений випадковими цілими числами в діапазоні від 1 до 50:
[45 39 31 29]
Вектор з квадратними коренями цих чисел:
[6.70820393 6.244998   5.56776436 5.38516481]
